### ISSUE TITLE
Add docs for running tests on multiple browsers

### ISSUE THREAD

**Issue by ChrisWren** [sauce-archives/pomade#2]
How can I run tests on multiple browsers and configure arbitrary desired caps for browsers? I only see a `default` platform to run on using a flat array to configure caps.

**Comment by ChrisWren** [comment]
ping @ryankirkman

**Comment by ryankirkman** [comment]
That functionality isn't in there yet. We need to port over the `@on_platforms` decorator.

**Comment by jlipps** [comment]
`@on_platforms`, oh boy.

**Comment by ryankirkman** [comment]
Don't worry jlipps, I'll get it ported

**Comment by ryankirkman** [comment]
@ChrisWren Just for you soldier: https://pypi.python.org/pypi/pomade/0.0.4

**Comment by ChrisWren** [comment]
Thanks!
